### ISSUE TITLE
do not group code by "maps, tuples, interfaces..." file.

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#16]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/maps.go#L1

File name should reflect it's contents to easily find what you want. So if you have some constants, it's better to store them in file when they used. And declare comment with what that map contains, what is key and what is value.

**Comment by essserrr** [comment]
done
