### ISSUE TITLE
it's type initialization, keep it in correct place

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#17]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/pvpFunctions.go#L38

you have makeNewCharacter function, so initialize that fields there. So you don't miss to init some fields when will use that function in other place.

**Comment by essserrr** [comment]
It had been fixed before your comment, hadn`t been submitted. My bad
