### ISSUE TITLE
if u need to pass many of struct fields to function, pass structure instead.

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#18]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/pvpFunctions.go#L17

Pass structure or pointer to a structure (since you initialize it) instead of long argument list. If you want to save function which gets only needed parameters, you can wrap one function into another, which will just call extended function with proper parameters. Keep it simple, stupid (KISS)

**Comment by essserrr** [comment]
It had been fixed before your comment, hadn`t been submitted. My bad
