### ISSUE TITLE
group argument types

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#20]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/pvpFunctions.go#L52

you can write `attacker, defender *pokemon, ..`

**Comment by awskii** [comment]
Lower you have timer and round init. In go when you say `var name type` variable `name` is initialized with zero value for that type. int*=0, float*=0.0 for string it's empty string and so on. 
so write 
```
var (
 round int64
 timer float64
)```

**Comment by essserrr** [comment]
Done
