### ISSUE TITLE
you abusing declarative programming patterns.

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#21]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/pvpFunctions.go#L80

here you have some methods with passes pointers here and there. Instead you can define special type Battle, which would store timer, round counter and so on, so you dont need to pass pointers, you have an access to them from method receiver. And that simplifies reading.

**Comment by essserrr** [comment]
done
