### ISSUE TITLE
what is your log? 

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#22]
https://github.com/essserrr/Solutions/blob/a496fea7728382e4f31796e64d3573b04da3a0a2/Project%201/pvpFunctions.go#L122

Since you have so much staff with your log, i'd prefer to define special type Log, and instead of that tricky append, you could write like `log.chargeMove(name, move)` and that method could use fmt.Sprintf(%s used charge move %q).

Also, if u do so, you will raise an ability to easily create method for fight reconstruction by it's log - it will be really easy to implement. Now your log looks more like a strange than effective and useful. Inside that log you could use slice of strings or whatever you want, but it will be hidden from that log users, kind of abstraction.

**Comment by essserrr** [comment]
Fixed
